version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "06:00"
  open-pull-requests-limit: 99
  reviewers:
  - rschlaefli
  ignore:
  - dependency-name: bitnami/wordpress
    versions:
    - 5.6.0.pre.debian.pre.10.pre.r4
